const { PrismaClient } = require('@prisma/client')
// const Bcrypt = require('bcrypt');

// import { links } from '../data/links'

const prisma = new PrismaClient()

async function main() {
 await prisma.user.create({
  data: {
   name: 'Superadmin 1',
   nip: '1991092320201011',
   email: `admin@blk9.com`,
   passwords: 'password',
   role: 'ADMIN'
  }
 });

 // await prisma.asset.createMany({
 //  data: dataLinks
 // });
}

main()
 .catch((e) => {
  console.error(e)
  process.exit(1)
 })
 .finally(async () => {
  await prisma.$disconnect()
 })

const dataLinks = [
 {
  name: "PC ",
  brand: "HP",
  type: "M01-F2001d",
  dimension: "15,5 x 33,5 x 30",
  material: "Elektronik",
  sum: 20,
  year: 2022,
  price: 15000000,
  from: "APBD",
  condition: true,
  goodCondition: 20,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Monitor",
  brand: "HP",
  type: "M01-F2001d",
  dimension: "21,5 inch",
  material: "Elektronik",
  sum: 20,
  year: 2022,
  price: 0,
  from: "APBD",
  condition: true,
  goodCondition: 20,
  kejuruanId: 1,
  note: "Bundle Komputer Pelatihan "
 },
 {
  name: "Mesin Cutting",
  brand: "Jinka",
  type: "Pro 1351",
  dimension: "163 x 34 x 45",
  material: "Elektronik",
  sum: 1,
  year: 2021,
  price: 7700000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Peraga Pelatihan"
 },
 {
  name: "Mesin Press Pin",
  brand: "Talent",
  type: "Talent",
  dimension: "29 x 16 x 36",
  material: "Logam",
  sum: 1,
  year: 2021,
  price: 2750000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Peraga Pelatihan"
 },
 {
  name: "Mesin Laminating",
  brand: "Inavatec",
  type: "A3-330",
  dimension: "50 x 26 x 9,5",
  material: "Elektronik",
  sum: 1,
  year: 2021,
  price: 300000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Peraga Pelatihan"
 },
 {
  name: "Mesin Spiral",
  brand: "GEMET",
  type: "31 WFO",
  dimension: "42 x 34 x 20",
  material: "Logam",
  sum: 1,
  year: 2021,
  price: 300000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Peraga Pelatihan"
 },
 {
  name: "Printer DTG",
  brand: "RIECAT",
  type: "DTG-SUPER",
  dimension: "65 x 76 x 38",
  material: "Elektronik",
  sum: 1,
  year: 2022,
  price: 31000000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Mesin printer sablon"
 },
 {
  name: "Mesin Hot Press",
  brand: "Fortex ",
  type: "FX-9500",
  dimension: "38,5 x 40 x 65",
  material: "Elektronik",
  sum: 1,
  year: 2022,
  price: 6000000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Mesin press sablon"
 },
 {
  name: "Printer",
  brand: "Canon ",
  type: "E610",
  dimension: "45 x 38 x 25",
  material: "Elektronik",
  sum: 1,
  year: 2019,
  price: 2500000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Printer kertas warna"
 },
 {
  name: "Printer",
  brand: "HP ",
  type: "Color Laser 150n",
  dimension: "39 x 31 x 21",
  material: "Elektronik",
  sum: 1,
  year: 2022,
  price: 3400000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Printer kertas warna"
 },
 {
  name: "Printer",
  brand: "HP ",
  type: "Laser Jet P1005",
  dimension: "35 x 22 x 20",
  material: "Elektronik",
  sum: 1,
  year: 2017,
  price: 3000000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Printer kertas monochrome"
 },
 {
  name: "Printer",
  brand: "HP ",
  type: "Laser Jet MFP M127fn",
  dimension: "41 x 32 x 32",
  material: "Elektronik",
  sum: 1,
  year: 2017,
  price: 3200000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Printer kertas monochrome"
 },
 {
  name: "Printer",
  brand: "HP ",
  type: "Laser Jet MFP M177fw",
  dimension: "41 x 32 x 32",
  material: "Elektronik",
  sum: 1,
  year: 2016,
  price: 2750000,
  from: "APBD",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Printer kertas monochrome"
 },
 {
  name: "UPS",
  brand: "Prolink",
  type: "Super Fast",
  dimension: "13 x 33 x 21",
  material: "Elektronik",
  sum: 5,
  year: 2016,
  price: 900000,
  from: "APBD",
  condition: true,
  goodCondition: 5,
  kejuruanId: 1,
  note: "Backup Energi Listrik"
 },
 {
  name: "APC",
  brand: "Prolink",
  type: "1100",
  dimension: "13 x 33 x 21",
  material: "Elektronik",
  sum: 5,
  year: 2015,
  price: 900000,
  from: "APBD",
  condition: true,
  goodCondition: 5,
  kejuruanId: 1,
  note: "Backup Energi Listrik"
 },
 {
  name: "Monitor",
  brand: "DELL",
  type: "P 2212 HB",
  dimension: "22 inch",
  material: "Elektronik",
  sum: 20,
  year: 2014,
  price: 900000,
  from: "APBN",
  condition: true,
  goodCondition: 5,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Sound",
  brand: "Altec Lansing",
  type: "BXR 1121",
  dimension: "20 x 20 x 20",
  material: "Elektronik",
  sum: 8,
  year: 2015,
  price: 530000,
  from: "APBN",
  condition: true,
  goodCondition: 8,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Monitor",
  brand: "LG",
  type: "W1953S",
  dimension: "18 inch",
  material: "Elektronik",
  sum: 20,
  year: 2012,
  price: 1200000,
  from: "APBN",
  condition: true,
  goodCondition: 18,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Genset",
  brand: "Honda",
  type: "EU 30 iIS",
  dimension: "40 x 60 x 58",
  material: "Elektronik",
  sum: 1,
  year: 2015,
  price: 28000000,
  from: "APBN",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Backup Energi Listrik"
 },
 {
  name: "Router",
  brand: "Microtik",
  type: "RB 2011U1AS-RM",
  dimension: "44,3 x 9,2 x 4,4",
  material: "Elektronik",
  sum: 1,
  year: 2018,
  price: 3750000,
  from: "APBN",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Jaringan"
 },
 {
  name: "PC",
  brand: "Rakitan",
  type: "",
  dimension: "18 x 43 x 41",
  material: "Elektronik",
  sum: 40,
  year: 2012,
  price: 7000000,
  from: "APBN",
  condition: true,
  goodCondition: 35,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Switch",
  brand: "CISCO",
  type: "Catalyst 2960",
  dimension: "44,3 x 9,2 x 4,4",
  material: "Elektronik",
  sum: 3,
  year: 2018,
  price: 1300000,
  from: "APBN",
  condition: true,
  goodCondition: 3,
  kejuruanId: 1,
  note: "Alat Jaringan"
 },
 {
  name: "AC",
  brand: "Panasonic",
  type: "1 Pk",
  dimension: "29 x 87 x 21",
  material: "Elektronik",
  sum: 6,
  year: 2013,
  price: 4500000,
  from: "APBN",
  condition: true,
  goodCondition: 6,
  kejuruanId: 1,
  note: "Pendingain Ruangan"
 },
 {
  name: "PC",
  brand: "Lenovo",
  type: "All in one",
  dimension: "24 inch",
  material: "Elektronik",
  sum: 2,
  year: 2021,
  price: 12750000,
  from: "APBN",
  condition: true,
  goodCondition: 2,
  kejuruanId: 1,
  note: "Komputer Pelatihan"
 },
 {
  name: "Projector",
  brand: "BenQ",
  type: "mx550",
  dimension: "28 x 22 x 16",
  material: "Elektronik",
  sum: 1,
  year: 2019,
  price: 6000000,
  from: "APBN",
  condition: true,
  goodCondition: 1,
  kejuruanId: 1,
  note: "Alat Peraga Pelatihan"
 },
 {
  name: "Meja Siswa",
  brand: "",
  type: "",
  dimension: "170 x 60 x 125",
  material: "Kayu",
  sum: 10,
  year: 2010,
  price: 2000000,
  from: "APBN",
  condition: true,
  goodCondition: 10,
  kejuruanId: 1,
  note: "Mejak komputer untuk 2 siswa"
 },
 {
  name: "Meja Siswa",
  brand: "",
  type: "",
  dimension: "120 x 60 x 100",
  material: "Kayu",
  sum: 20,
  year: 2010,
  price: 2300000,
  from: "APBN",
  condition: true,
  goodCondition: 20,
  kejuruanId: 1,
  note: "Meja komputer siswa"
 },
 {
  name: "Meja Kerja",
  brand: "",
  type: "",
  dimension: "100 x 80 x 100",
  material: "Kayu + Kaca",
  sum: 3,
  year: 2010,
  price: 2500000,
  from: "APBN",
  condition: true,
  goodCondition: 3,
  kejuruanId: 1,
  note: "Meja kerja pegawai"
 },
 {
  name: "Almari",
  brand: "",
  type: "",
  dimension: "100x 50 x 200",
  material: "Kayu + Kaca",
  sum: 2,
  year: 2010,
  price: 2100000,
  from: "APBN",
  condition: true,
  goodCondition: 2,
  kejuruanId: 1,
  note: "Almari peralatan pelatihan"
 },
 {
  name: "Almari",
  brand: "Brother",
  type: "",
  dimension: "60 x 60 x 150",
  material: "Logam",
  sum: 2,
  year: 2000,
  price: 2750000,
  from: "APBN",
  condition: true,
  goodCondition: 2,
  kejuruanId: 1,
  note: "Almari dokumen"
 },
]
